package cn.test.entity;
// Generated 2017-5-14 19:18:52 by Hibernate Tools 3.6.0.Final

/**
 * RolePrivilegeId generated by hbm2java
 */
public class RolePrivilegeId implements java.io.Serializable {

	private String roleId;
	private String code;

	public RolePrivilegeId() {
	}

	public RolePrivilegeId(String roleId, String code) {
		this.roleId = roleId;
		this.code = code;
	}

	public String getRoleId() {
		return this.roleId;
	}

	public void setRoleId(String roleId) {
		this.roleId = roleId;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RolePrivilegeId))
			return false;
		RolePrivilegeId castOther = (RolePrivilegeId) other;

		return ((this.getRoleId() == castOther.getRoleId()) || (this.getRoleId() != null
				&& castOther.getRoleId() != null && this.getRoleId().equals(castOther.getRoleId())))
				&& ((this.getCode() == castOther.getCode()) || (this.getCode() != null && castOther.getCode() != null
						&& this.getCode().equals(castOther.getCode())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getRoleId() == null ? 0 : this.getRoleId().hashCode());
		result = 37 * result + (getCode() == null ? 0 : this.getCode().hashCode());
		return result;
	}

}
