package cn.test;
// Generated 2017-5-8 19:24:48 by Hibernate Tools 3.6.0.Final

/**
 * UserRole generated by hbm2java
 */
public class UserRole implements java.io.Serializable {

	private String userRoleId;
	private User user;
	private Role role;

	public UserRole() {
	}

	public UserRole(String userRoleId) {
		this.userRoleId = userRoleId;
	}

	public UserRole(String userRoleId, User user, Role role) {
		this.userRoleId = userRoleId;
		this.user = user;
		this.role = role;
	}

	public String getUserRoleId() {
		return this.userRoleId;
	}

	public void setUserRoleId(String userRoleId) {
		this.userRoleId = userRoleId;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public Role getRole() {
		return this.role;
	}

	public void setRole(Role role) {
		this.role = role;
	}

}
