package cn.pbq.entity;
// Generated 2017-5-8 19:24:48 by Hibernate Tools 3.6.0.Final

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * Info generated by hbm2java
 */
public class Info implements java.io.Serializable {

	private String infoId;
	private String infoType;
	private String title;
	private String source;
	private String content;
	private String memo;
	private String creator;
	private Date createTime;
	private String state;


	
	
	public Info() {
	}

	public Info(String infoId) {
		this.infoId = infoId;
	}
	
	public Info(String infoId, String state) {
		this.infoId = infoId;
		this.state = state;
	}


	public Info(String infoId, String infoType, String title, String source, String content, String memo,
			String creator, Date createTime, String state) {
		this.infoId = infoId;
		this.infoType = infoType;
		this.title = title;
		this.source = source;
		this.content = content;
		this.memo = memo;
		this.creator = creator;
		this.createTime = createTime;
		this.state = state;
	}

	public String getInfoId() {
		return this.infoId;
	}

	public void setInfoId(String infoId) {
		this.infoId = infoId;
	}

	public String getInfoType() {
		return this.infoType;
	}

	public void setInfoType(String infoType) {
		this.infoType = infoType;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getSource() {
		return this.source;
	}

	public void setSource(String source) {
		this.source = source;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public String getMemo() {
		return this.memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}

	public String getCreator() {
		return this.creator;
	}

	public void setCreator(String creator) {
		this.creator = creator;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

}
