package cn.pbq.entity;
// Generated 2017-5-8 15:11:03 by Hibernate Tools 5.1.0.Alpha1

/**
 * RolePrivilege generated by hbm2java
 */
public class RolePrivilege implements java.io.Serializable {

	private RolePrivilegeId id;

	public RolePrivilege() {
	}

	public RolePrivilege(RolePrivilegeId id) {
		this.id = id;

	}

	public RolePrivilegeId getId() {
		return this.id;
	}

	public void setId(RolePrivilegeId id) {
		this.id = id;
	}



}
